
//! Autogenerated weights for pallet_template
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `_`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ../../target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_template
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/template/src/weights.rs
// --template
// ../../.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame::{deps::frame_support::weights::constants::RocksDbWeight, prelude::*};
use core::marker::PhantomData;

/// Weight functions needed for pallet_bridge.
pub trait WeightInfo {
	fn send_message() -> Weight;
	fn execute_cross_chain_call() -> Weight;
}

/// Weights for pallet_bridge using the Substrate node and recommended hardware.
#[cfg_attr(
    not(feature = "std"),
    deprecated(
        note = "SubstrateWeight is auto-generated and should not be used in production. Replace it with runtime benchmarked weights."
    )
)]
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Bridge MessageStatus (r:0 w:1)
	/// Proof: Bridge MessageStatus (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn send_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: Bridge MessageStatus (r:0 w:1)
	/// Proof: Bridge MessageStatus (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn execute_cross_chain_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Bridge MessageStatus (r:0 w:1)
	/// Proof: Bridge MessageStatus (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn send_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: Bridge MessageStatus (r:0 w:1)
	/// Proof: Bridge MessageStatus (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn execute_cross_chain_call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
